platform:ios,'7.0'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'MJExtension'
pod 'FMDB'
pod 'Masonry'
pod 'MJRefresh'
pod 'CocoaLumberjack'
pod 'ReactiveCocoa'
pod 'LNSideMenu', '~> 1.0.1'
